name: slack-notify
description: You can notify slack of GitHub Actions.
author: ableco
inputs:
  status:
    description: Specify success or failure or cancelled or custom.
    required: true
    default: "success"
runs:
  using: node12
  main: index.js
branding:
  icon: bell
  color: blue
